"use client";

import { useEffect, useState } from "react";
import { BookOpen, CalendarDays, Users } from "lucide-react";
import api from "../lib/api";

export default function GuideDashboard() {
  const [projects, setProjects] = useState<Array<{ id: string; title: string; status: string; member_count: number }>>([]);
  useEffect(() => { api.get("/projects").then(({ data }) => setProjects(data.projects || [])).catch(() => undefined); }, []);
  return <main className="min-h-screen bg-slate-50 px-5 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">Guide workspace</p><h1 className="mt-2 text-3xl font-bold">Assigned Teams</h1><p className="mt-3 text-sm text-slate-500">Review assigned teams and manage project milestones.</p><div className="mt-8 grid gap-5 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><BookOpen className="text-indigo-600" size={21} /><p className="mt-4 text-sm text-slate-500">Assigned projects</p><p className="mt-1 text-3xl font-bold">{projects.length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Users className="text-indigo-600" size={21} /><p className="mt-4 text-sm text-slate-500">Active teams</p><p className="mt-1 text-3xl font-bold">{projects.filter((project) => project.status !== "COMPLETED").length}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><CalendarDays className="text-indigo-600" size={21} /><p className="mt-4 text-sm text-slate-500">Review schedule</p><p className="mt-1 text-3xl font-bold">View</p></div></div><section id="teams" className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Assigned teams</h2><div className="mt-4 divide-y divide-slate-100">{projects.map((project) => <div key={project.id} className="flex items-center justify-between py-4"><div><p className="font-semibold">{project.title || "Untitled project"}</p><p className="text-sm text-slate-500">{project.member_count} members</p></div><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{project.status}</span></div>)}{!projects.length && <p className="py-6 text-sm text-slate-500">Sign in as a guide to load assigned teams.</p>}</div></section></div></main>;
}
